image: node:lts

variables:
  APNSCP_THEME_PATH: "dist/"

cache:
  paths:
    - node_modules/

before_script:
  - mkdir -p $APNSCP_THEME_PATH
  - yarn install
  - yarn global add grunt-cli node-sass clean-css-cli

build-stage:
  script:
    - grunt dist
  artifacts:
    paths:
      - $APNSCP_THEME_PATH
